#!/usr/bin/env bash
# Copy the shared accounts SDK and UI elements into the repo.
#
# WHY THIS EXISTS
#
# `apps/web/src/lib/account.ts` imports `@openapps/sdk` and `@openapps/ui`.
# Those two packages live in a private monorepo one level above this folder,
# and are shared across every product in the suite. This repository is
# public and standalone: a clone has no parent, so `file:../../../sdk/ts`
# resolves to nothing and `npm install` fails before it starts.
#
# The suite's answer -- already what opencapture and openpdfedit do -- is to
# vendor the *built* packages and depend on them by a path inside the repo.
# The vendored copy is a build input, like a lockfile: checked in, so a clone
# builds offline; regenerated by this script, so it never drifts by hand.
#
# Only `dist/` and `package.json` are copied. `src/`, tests and node_modules
# are not ours to redistribute here and are not needed to build against.
#
# Usage, from the repo root, with the private monorepo checked out above it:
#   bash scripts/vendor-openapps.sh
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="${OPENAPPS_ROOT:-$(cd "$here/.." && pwd)}"
dest="$here/apps/web/vendor/openapps"

for pair in "sdk:$src/sdk/ts" "ui:$src/ui-elements"; do
  name="${pair%%:*}"
  from="${pair#*:}"
  if [ ! -d "$from/dist" ]; then
    echo "error: $from/dist is missing." >&2
    echo "       Build it first (npm run build in $from), or set OPENAPPS_ROOT" >&2
    echo "       to the monorepo that holds it." >&2
    exit 1
  fi
  rm -rf "$dest/$name"
  mkdir -p "$dest/$name"
  cp -R "$from/dist" "$dest/$name/dist"
  # The published package.json, minus the workspace-only fields. The peer
  # dependency on @openapps/sdk is dropped: here the two are siblings on
  # disk, and npm cannot satisfy a peer range from a file: path.
  python3 - "$from/package.json" "$dest/$name/package.json" <<'PY'
import json, sys
src, out = sys.argv[1], sys.argv[2]
d = json.load(open(src, encoding="utf-8"))
keep = ("name", "version", "type", "main", "module", "types", "exports",
        "dependencies", "license")
v = {k: d[k] for k in keep if k in d}
json.dump(v, open(out, "w", encoding="utf-8"), indent=2)
open(out, "a", encoding="utf-8").write("\n")
PY
  echo "vendored $name  <- $from"
done

echo
echo "now: (cd apps/web && npm install)"
